# MLOps Project Configuration
random_state: 42

model:
  catboost:
    # Core hyperparameters
    n_estimators: 5
    learning_rate: 0.1
    max_depth: 6
    l2_leaf_reg: 3
    random_state: 42

    # CatBoost specific parameters
    loss_function: 'CrossEntropy'
    eval_metric: 'AUC'
    use_best_model: true
    early_stopping_rounds: 200
    verbose: 500
    allow_writing_files: false
    task_type: 'CPU'

# Training configuration
training:
  cv_folds: 5
  random_state: 42
  shuffle: true

  # Validation thresholds for model promotion
  validation_thresholds:
    min_roc_auc: 0.80
    min_accuracy: 0.75
    max_cv_std: 0.05

# Data configuration
data:
  raw_dir: 'data/raw'
  processed_dir: 'data/processed'
  models_dir: 'models'
  reference_dir: 'data/reference'
  current_dir: 'data/current'

  # Data ingestion
  dataset_type: 'train'
  target_column: 'y'

  # Feature engineering
  test_size: 0.2
  stratify: true

# MLflow configuration
mlflow:
  tracking_uri: 'http://localhost:5000'
  experiment_name: 'bank-marketing-catboost'

  # Artifact logging
  log_artifacts: true
  log_shap_plots: true
  log_feature_importance: true
  log_drift_reports: true

# FastAPI configuration
api:
  host: '0.0.0.0'
  port: 8000
  title: 'Bank Marketing Prediction API'
  description: 'ML API for predicting bank term deposit subscriptions'
  version: '1.0.0'

# Airflow configuration
airflow:
  # DAG scheduling
  training_schedule: '@daily'
  drift_check_schedule: '@hourly'
  deployment_schedule: null  # Triggered by training completion

  # Task configuration
  retries: 2
  retry_delay_minutes: 5

  # Email alerts (optional)
  email_on_failure: false
  email_on_retry: false
  email: ['your-email@example.com']

# Comprehensive Drift Detection Configuration
drift:
  # Reference dataset configuration
  reference_data:
    path: 'data/reference/reference.parquet'
    auto_generate: true  # Generate from training data if not exists

  # Current batch configuration for monitoring
  current_batch:
    output_path: 'data/current/current_batch.parquet'
    batch_size: 500
    apply_drift: false  # Set to true for testing drift scenarios

  # Drift thresholds for alerts
  thresholds:
    data_drift_p_value: 0.05
    target_drift_p_value: 0.05
    feature_drift_threshold: 0.1

  # Bank marketing specific feature mappings
  features:
    numerical:
      - 'age'
      - 'balance'
      - 'duration'
      - 'campaign'
      - 'pdays'
      - 'previous'
    categorical:
      - 'job'
      - 'marital'
      - 'education'
      - 'default'
      - 'housing'
      - 'loan'
      - 'contact'
      - 'day'
      - 'month'
      - 'poutcome'

  # Drift simulation scenarios for testing
  scenarios:
    severe_data_drift:
      description: "Significant distribution changes requiring immediate action"
      data_drift:
        target_column: 'y'
        numerical_drift:
          age:
            type: "gaussian_noise"
            noise_std: 0.6
            description: "Major demographic shift"
          balance:
            type: "shift_mean"
            shift_factor: 0.5
            description: "Economic conditions affecting customer balances"
          duration:
            type: "outlier_injection"
            outlier_percentage: 0.4
            description: "System issues causing call duration anomalies"
        categorical_drift:
          job:
            type: "category_shift"
            shift_percentage: 0.3
            description: "Employment sector changes"
          marital:
            type: "category_shift"
            shift_percentage: 0.3
            description: "Marital status distribution changes"

    concept_drift:
      description: "Changes in customer behavior patterns"
      concept_drift:
        target_column: 'y'
        concept_drift_type: "label_flip"
        label_flip_percentage: 0.25
        description: "Customer subscription behavior changes due to market conditions"

# Evidently AI Report Configuration
evidently:
  reports:
    data_drift:
      enabled: true
      save_path: 'reports/data_drift.html'
      presets: ['DataDriftPreset']
    target_drift:
      enabled: true
      save_path: 'reports/target_drift.html'
      presets: ['TargetDriftPreset']
    data_quality:
      enabled: true
      save_path: 'reports/data_quality.html'
      presets: ['DataQualityPreset']
    classification_performance:
      enabled: true
      save_path: 'reports/classification_performance.html'
      presets: ['ClassificationPreset']

  # Report generation settings
  reference_period: 30  # days
  current_period: 7     # days

# Original drift configuration (legacy, kept for backward compatibility)
drift_legacy:
  # Evidently AI settings
  reference_data_path: 'data/reference/reference.parquet'
  current_data_path: 'data/current/current_batch.parquet'

  # Drift thresholds
  data_drift_threshold: 0.05
  target_drift_threshold: 0.05

  # Simulation parameters for testing
  noise_level: 0.1
  label_flip_probability: 0.05

# Logging configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

  # File logging (optional)
  log_to_file: false
  log_file_path: 'logs/pipeline.log'

# Environment configuration
environment:
  # Development/Production flags
  debug: false
  testing: false

  # Resource limits
  max_memory_gb: 8
  max_cpu_cores: 4

  # Docker configuration
  docker:
    postgres_db: 'mlflow_db'
    postgres_user: 'mlflow_user'
    postgres_password: 'mlflow_password'

# Deployment configuration
deployment:
  model_registry:
    champion_model_name: 'bank-marketing-champion'
    challenger_model_name: 'bank-marketing-challenger'

  promotion_criteria:
    min_accuracy_improvement: 0.02
    min_auc_improvement: 0.01
    max_performance_degradation: 0.05

  api_reload:
    enabled: true
    reload_endpoint: 'http://fastapi:8000/reload'

# Monitoring configuration
monitoring:
  drift_detection:
    enabled: true
    check_frequency: '@hourly'
    alert_channels: ['log', 'email']  # Can add 'slack', 'teams'

  model_performance:
    enabled: true
    performance_threshold: 0.75
    alert_on_degradation: true

  data_quality:
    enabled: true
    missing_data_threshold: 0.1
    duplicate_threshold: 0.05